#!/usr/bin/env sh

set -e
cd $(dirname $0)

if [ ! -f build/build_cid ]; then
  >&2 echo "Docker container is not active. Run \`make\` first."
  exit 1
fi


case "$#" in
"0")
  `make print_run_cmd`
  ;;
"1")
  `make print_run_cmd` <"$1"
  ;;
"2")
  `make print_run_cmd` <"$1" >"$2"
  ;;
*)
  >&2 echo "Unexpected number of arguments: $#"
  exit 1
esac
