#!/usr/bin/env bash

set -e
cd $(dirname $0)

if [ ! -f build/build_cid ]; then
  >&2 echo "Docker container is not active. Run \`make\` first."
  exit 1
fi

ARGS=""
while [[ $1 == -* ]]; do
  ARGS="$ARGS $1";
  shift;
done

case "$#" in
"0")
  `make print_run_cmd` $ARGS
  ;;
"1")
  `make print_run_cmd` $ARGS <"$1"
  ;;
"2")
  `make print_run_cmd` $ARGS <"$1" >"$2"
  ;;
*)
  >&2 echo "Unexpected number of arguments: $#"
  exit 1
esac
